### ISSUE TITLE
version information unavailible

### ISSUE THREAD

**Issue by deleteriousEffect** [hdjr/install_drbdtop#1]
Hi, just tries this out and it works really well!

There is one small quirk with the way that drbdtop find it's version info:  we use ldflags to get the version info from git at build time.

If you really wanted the version info, you could clone it down and build it with `make build` this would put the binary in the `_build` directory in the project root.

**Comment by hdjr** [comment]
Hi haySwim!

First off, thanks for the feedback.

Could you clarify what you mean for me please? Are you stating to build go with the ldflags or drbdtop? This is my first time using go so I'm unfamiliar with it.

Thanks again for the help.

**Comment by deleteriousEffect** [comment]
Sure, if you look at the makefile for drbdtop you can see the flags we're passing to `go build`. ldflags let us set variables at build time, and that's what we do for drbdtop's version. The version variable is in main.go.

**Comment by hdjr** [comment]
haySwim,

I hope you had a good weekend. Thanks for the help. I found that there were missing dependencies in the go directory which is why it couldn't find the ldflags.

Here is the error I was getting.
~~~
[root@drbd drbdtop]# make build
go build -ldflags "-X main.Version=`git describe --tags --always --dirty`"
drbdtop.go:28:2: cannot find package "github.com/linbit/drbdtop/pkg/collect" in any of:
        /usr/local/go/src/github.com/linbit/drbdtop/pkg/collect (from $GOROOT)
        /root/go/src/github.com/linbit/drbdtop/pkg/collect (from $GOPATH)
drbdtop.go:29:2: cannot find package "github.com/linbit/drbdtop/pkg/display" in any of:
        /usr/local/go/src/github.com/linbit/drbdtop/pkg/display (from $GOROOT)
        /root/go/src/github.com/linbit/drbdtop/pkg/display (from $GOPATH)
drbdtop.go:30:2: cannot find package "github.com/linbit/drbdtop/pkg/resource" in any of:
        /usr/local/go/src/github.com/linbit/drbdtop/pkg/resource (from $GOROOT)
        /root/go/src/github.com/linbit/drbdtop/pkg/resource (from $GOPATH)
drbdtop.go:26:2: cannot find package "gopkg.in/alecthomas/kingpin.v2" in any of:
        /usr/local/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOROOT)
        /root/go/src/gopkg.in/alecthomas/kingpin.v2 (from $GOPATH)
make: *** [build] Error 1
~~~

With your help, I was able to get it working.
[root@host-192-168-10-114 ~]# drbdtop/drbdtop --version
v0.1-1-g2c93b48
 

- Hopefully this week I can get it implemented in the script.

**Comment by hdjr** [comment]
Happy Friday @haySwim ! The changes have been made to the script. Please test this on your end if possible and let me know if you have any further suggestions.

Thanks!
